### PR TITLE
Update CLI version for integration tests

### PR DESCRIPTION
**Pull request by shati-patel**
[CodeQL CLI 2.6.1 is](https://github.com/github/codeql-cli-binaries/releases/tag/v2.6.1) released! 🚢 

## Checklist

- [ ] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [ ] Issues have been created for any UI or other user-facing changes made by this pull request.
- [ ] `@github/docs-content-codeql` has been cc'd in all issues for UI or other user-facing changes made by this pull request.

### CODE REVIEW

**Review by edoardopirovano — APPROVED** [review]

**Comment by edoardopirovano** [comment]
Looks like there's a test that needs updating but otherwise this LGTM!

**Comment by shati-patel** [comment]
Ah yes, looks like a qlpack issue - I'll try to fix that 😄

**Comment by shati-patel** [comment]
Yay, tests are passing again! @edoardopirovano, would you mind taking a quick look that my test changes look sensible?

**Comment by edoardopirovano** [comment]
Seems reasonable, yes! It's a little unfortunate we can't easily test that we get the exact name of the pack but I don't see an easy way of doing that given it will have different names depending on the CLI version.

**Comment by shati-patel** [comment]
> It's a little unfortunate we can't easily test that we get the exact name of the pack but I don't see an easy way of doing that given it will have different names depending on the CLI version.

Yes, I couldn't see how to do this... 😞 

I'll merge this PR since it'll hopefully also fix tests on https://github.com/github/vscode-codeql/pull/946, but we can try making the tests more specific again later 😅

**Pull request merged**
