### PR TITLE
Create version bump PRs in draft mode

### PR DESCRIPTION
**Pull request by shati-patel**
Currently, the token we use to create these PRs doesn't have sufficient permissions to set off PR checks. As mentioned yesterday, maybe if we create the PR as a draft and have a real person mark the PR as "ready-for-review", this will be enough to start PR checks.

## Checklist

- [N/A] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [N/A]] Issues have been created for any UI or other user-facing changes made by this pull request.
- [[N/A] `@github/docs-content-codeql` has been cc'd in all issues for UI or other user-facing changes made by this pull request.

### CODE REVIEW

**Comment by aeisenberg** [comment]
I wonder if the workflow failures here are because you pushed this to your fork of vscode-codeql. If it keeps failing, maybe try opening another PR, but from a branch on the core repo.

**Comment by shati-patel** [comment]
> I wonder if the workflow failures here are because you pushed this to your fork of vscode-codeql. If it keeps failing, maybe try opening another PR, but from a branch on the core repo.

(Ah yes, good point about the fork!)
Though I've now removed the `on:pull_request` trigger, which seemed reasonable. Do we ever want to run the releases workflow on PRs? I feel like that will always fail since we tag the release with the `github.ref`, which doesn't make sense for PRs 🤔

**Comment by adityasharad** [comment]
We had the `pull_request` trigger only for testing changes to the release workflow itself (historically, when workflow dispatch didn't exist). If the workflow can be run on dispatch then that's good enough for testing.

**Comment by aeisenberg** [comment]
> If the workflow can be run on dispatch then that's good enough for testing.

Though, this will only work if the branch is on the main repo, not a fork.

**Review by aeisenberg — APPROVED** [review]
I think this is fine as long as we remember that testing workflow changes will need to happen on the main repo.

**Pull request merged**
