### PR TITLE
Remove LGTM references and commands

### PR DESCRIPTION
**Pull request by aeisenberg**
LGTM has been decommissioned. All code and tests for downloading LGTM databases should be removed.

Note that there will need to be some docs changes for this to remove the docs around LGTM integration. This can happen later. 

## Checklist

- [ ] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [x] Issues have been created for any UI or other user-facing changes made by this pull request.
- [ ] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/codeql-for-visual-studio-code) repo and add the `ready-for-doc-review` label there.

### CODE REVIEW

**Review by aibaars — APPROVED** [review]
LGTM ;-)

**Review by shati-patel — APPROVED** [review]
💥 

I think you can also remove the lgtm SVGs! (We can tidy those up later though—main thing is removing the command/tests ✅ )

**Comment by aeisenberg** [comment]
I'll do that. Also need to add a change note.

**Comment by aeisenberg** [comment]
Looks like no change note is necessary since the removal was already announced earlier. I think the behaviour was kept around behind a feature flag.

I removed the svgs.

**Pull request merged**
