### PR TITLE
tecnical alterations for secure protocol

### PR DESCRIPTION
**Pull request by haller33**
Replace this with a description of the changes your pull request makes.

## Checklist

- [ ] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [ ] Issues have been created for any UI or other user-facing changes made by this pull request.
- [ ] `@github/docs-content-dsp` has been cc'd in all issues for UI or other user-facing changes made by this pull request.

### CODE REVIEW

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 1

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 2

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 3

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 4

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 5

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 6

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 7

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 8

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 9

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 10

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 11

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 12

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 14

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 15

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 16

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 17

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 18

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 19

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 20

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 21

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 22

**Comment by haller33** [comment]
TECHNICAL ALTERATIONS FOR SECURE PROTOCOL 23

**Comment by hmakholm** [comment]
Spam.

**Pull request closed without merging**
