### PR TITLE
Remove failing integration test

### PR DESCRIPTION
**Pull request by jcreedcmu**
This works around but does not fundamentally address https://github.com/github/vscode-codeql/issues/493.

### CODE REVIEW

**Comment by aeisenberg** [comment]
Yep. As soon as I updated my VS Code, I'm getting the same problem locally.

**Comment by adityasharad** [comment]
Can we test against both a stable version and the latest? It looks like useful information that the tests started failing when VS Code made a breaking change, and I don't want to lose the ability to discover such problems early.

**Comment by aeisenberg** [comment]
I think before we merge this, we need to figure out where the problem came from. I just looked at the vs code sources and neither [`uri.ts`](https://github.com/microsoft/vscode/blob/master/src/vs/base/common/uri.ts) nor https://github.com/microsoft/vscode/blob/master/src/vs/workbench/api/common/shared/webview.ts have any relevant changes. There could be other related changes that I haven't seen, though.

**Comment by jcreedcmu** [comment]
I think I've determined that the underlying problem is that we *were* dangerously relying on the underlying representation of vscode resource URIs, (see https://github.com/microsoft/vscode/pull/97777 for some breadcrumbs into the process of that change) and that underlying representation changed out from under us.

However, thankfully, we *are* no longer relying on that representation --- it was only used to get back the file uri for purposes of `fetch`ing directly from the webview. Because of progress towards cli result parsing, this is dead code and that failing test is no longer relevant.

**Pull request merged**
