### PR TITLE
security update

### PR DESCRIPTION
**Pull request by SMSTUNITS**
Replace this with a description of the changes your pull request makes.

## Checklist

- [x] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [ ] Issues have been created for any UI or other user-facing changes made by this pull request.
- [ ] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/codeql-for-visual-studio-code) repo and add the `ready-for-doc-review` label there.

### CODE REVIEW

**Comment by aeisenberg** [comment]
Thank you for your contribution. Please remove the new security.md and codeql-analysis files and we can take a closer look at this PR. On the surface it looks fine. Also, can you squash the additional commits from your fork?

**Review by aeisenberg — APPROVED** [review]
Looks good.

**Comment by aeisenberg** [comment]
Can you fix the merge conflicts? I tried, but can't upload the changes back to your repo.

**Comment by ErcetinGuler** [comment]
çalışıcağım

**Comment by aeisenberg** [comment]
Closing in favour of https://github.com/github/vscode-codeql/pull/1092

**Pull request closed without merging**
