### PR TITLE
Add command to sort databases by name and date added

### PR DESCRIPTION
**Pull request by aeisenberg**
This assumes that we will be adding other sorting mechanisms in the
future, like sort by data added.

Not happy with the icon I chose, but I didn't want to spend too much
time creating a new one.

## Checklist

- [x] [CHANGELOG.md](../extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [x] Issues have been created for any UI or other user-facing changes made by this pull request.
- [x] `@github/product-docs-dsp` has been cc'd in all issues for UI or other user-facing changes made by this pull request.

### CODE REVIEW

**Comment by aeisenberg** [comment]
Relates to #322.

**Comment by aeisenberg** [comment]
Fixes #322

**Comment by jcreedcmu** [comment]
Nice, lgtm. I don't see any obvious way of changing the command icons dynamically, to e.g. show the current sort order, but this seems okay to me as-is. 

@github/product-docs-dsp does this need docs?

**Comment by aeisenberg** [comment]
@github/product-docs-dsp There are some changes in this PR that will require a mention in the docs. This PR adds the ability to sort databases by name or by date added from the databases tree view.

**Comment by shati-patel** [comment]
Thanks for the ping - I've opened an [issue](https://github.com/github/semmle-docs/issues/70) to update the docs 📝

**Pull request merged**
