### PR TITLE
Force use of single quotes in formatter settings

### PR DESCRIPTION
**Pull request by aeisenberg**
This PR enforces double quotes in the formatting rules. Turns out this was never enforced before, even though that was (mostly) the de facto style. 

This PR also will fail linting (and hence any `git push`) if there are any formatting warnings.

Since reformatting is now happening on commit, it means that running `git commit` will take longer for `eslint` to run. I'm ok to remove this, and to run `eslint` on push instead (ie- a push will fail if formatting is off).

### CODE REVIEW

**Comment by dbartol** [comment]
The single quotes may all be my fault. Bad habit carried over from PowerShell of all places. My bad.

**Comment by aeisenberg** [comment]
I actually prefer single quotes as well. But, this project was sort of using half and half. I'm just trying to enforce consistency.

**Comment by jcreedcmu** [comment]
If we all prefer single quotes (as I do as well) is there any way to enforce that instead?

**Comment by aeisenberg** [comment]
Let me change this PR to single quotes. I'll wait a little bit in order to get my other changes in first.

**Pull request merged**
