### PR TITLE
Split codeQL.copyVariantAnalysisRepoList into two commands

### PR DESCRIPTION
**Pull request by robertbrignull**
Fixes https://github.com/github/vscode-codeql/security/code-scanning/461

`codeQL.copyVariantAnalysisRepoList` is used from two places, but they're both internal so it's trivial to split the command into two.

## Checklist

- [ ] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [ ] Issues have been created for any UI or other user-facing changes made by this pull request.
- [ ] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/codeql-for-visual-studio-code) repo and add the `ready-for-doc-review` label there.

### CODE REVIEW

**Review by shati-patel — APPROVED** [review]
Seems reasonable! Though I'm slightly confused that we now have a lot of command identifiers referencing the same "action". I _think_ it makes sense, since some of them are just the user-facing ones, others are the internal commands? 🤔 

e.g. We already have `codeQLQueryHistory.copyRepoList`, so do we need to define `codeQL.copyVariantAnalysisRepoListQueryHistory` separately?

**Comment by robertbrignull** [comment]
@shati-patel, you raise a very good question. Looking into it more, I agree we don't need to have `codeQLQueryHistory.copyRepoList` immediately delegate to `codeQL.copyVariantAnalysisRepoListQueryHistory`. In fact I don't think we gain anything by having these extra commands and we can delete `codeQL.copyVariantAnalysisRepoListQueryHistory` and `codeQL.copyVariantAnalysisRepoListView`. In both cases we can call `VariantAnalysisManager.copyRepoListToClipboard` directly and there's no reason not to.

The only thing we then have to consider is if we're still logging enough telemetry, so I've added in some telemetry when copying repo lists. This mirrors what we do for exporting results which is defined just next to it.

**Review by shati-patel — APPROVED** [review]
Thanks for looking into this in some more detail! Looks good to me locally too ✨

**Comment by robertbrignull** [comment]
> the failing test looks legit though 😅

Yep, I wasn't thinking properly when I wrote that. It should be mocking the right function now 😅

**Pull request merged**
