### PR TITLE
Ensure the `logFileLocation` is set

### PR DESCRIPTION
**Pull request by aeisenberg**
`logFileLocation` was not set after a query finishes running. I don't know when this bug was introduced. I think it goes as far back as the refactor to remove the old query server.

Replace this with a description of the changes your pull request makes.

## Checklist

- [x] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [x] Issues have been created for any UI or other user-facing changes made by this pull request.
- [x] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/codeql-for-visual-studio-code) repo and add the `ready-for-doc-review` label there.

### CODE REVIEW

**Review by angelapwen — APPROVED** [review]
:shipit:

**Comment by aeisenberg** [comment]
Thanks for the review. Still need to add a change note.

**Comment by aeisenberg** [comment]
The code scanning warning was legitimate since there was a value being assigned in the constructor parameter list as well as the constructor body. I refactored a bit so there is no warning.

**Comment by angelapwen** [comment]
> The code scanning warning was legitimate since there was a value being assigned in the constructor parameter list as well as the constructor body. I refactored a bit so there is no warning.

Ah I see.. I think the location it showed up on was a bit misleading (because it didn't show on any assignment). Thanks!

**Review by angelapwen — APPROVED** [review]

**Pull request merged**
