### PR TITLE
Upgrade node version minimum requirement

### PR DESCRIPTION
**Pull request by charisk**
I believe we're expecting use of v15 and above so I've updated the engine definition.

## Checklist
N/A:
- [ ] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [ ] Issues have been created for any UI or other user-facing changes made by this pull request.
- [ ] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/codeql-for-visual-studio-code) repo and add the `ready-for-doc-review` label there.

### CODE REVIEW

**Review by shati-patel — APPROVED** [review]
Thanks, makes sense! 🚢

**Comment by edoardopirovano** [comment]
Should we not also be checking in an updated `package-lock.json`?

**Review by aeisenberg — COMMENTED** [review]
It's a little strange that we have `"@types/node": "^16.11.25"` in dev dependencies, but the minimum node version is 15. Can we synchronize the two? And also, the package lock should be updated as @edoardopirovano mentions.

**Comment by aeisenberg** [comment]
We also need to make sure that we run the internal integration tests using the same version of node. This is something I can take care of.

**Pull request merged**
