### PR TITLE
Remove 'qhelp' as global alias for 'xml' filetype

### PR DESCRIPTION
**Pull request by jcreedcmu**
Fixes https://github.com/github/vscode-codeql/issues/339.

### CODE REVIEW

**Comment by jcreedcmu** [comment]
I think this is the right thing to do; I thought the aliases were scoped to the file extension being added, but apparently not.

**Comment by aeisenberg** [comment]
Odd. but when I try your PR, my `qhelp` files are displayed as `html`. And I don't even see `qhelp` as an option.

**Comment by jcreedcmu** [comment]
Huh, that's strange and I don't know how to explain that yet. I wouldn't expect to see qhelp as an option, precisely because I removed it as an alias --- the intent of this PR is to restore the situation to there only being a notion of a file "being" xml, and removing the possibility of a file being of type qhelp, but preserving that the `.qhelp` extension should cause them to be viewed as xml. Can you repro the behavior you're seeing with this PR but with all other extensions disabled?

**Comment by aeisenberg** [comment]
I can't explain what happened before. I tried this again and this seems to be working as expected. This just associates qhelp as an xml file, which I think is perfectly fine. In the future, we can consider creating a proper qhelp language type.

**Pull request merged**
