### PR TITLE
v1.7.2

### PR DESCRIPTION
**Pull request by aeisenberg**
Release prep.

### CODE REVIEW

**Review by angelapwen — APPROVED** [review]
😸

**Comment by angelapwen** [comment]
Test flakes, I think? Re-running

**Comment by aeisenberg** [comment]
Yes. I don't remember the flakes being this bad.

**Comment by angelapwen** [comment]
Yep... another one.

**Comment by aeisenberg** [comment]
This deserves a closer look. I'm not sure what is causing these new flakes.

**Pull request merged**
