### PR TITLE
Fix running build on node 18

### PR DESCRIPTION
**Pull request by aeisenberg**
Two problems:

1. source-map@0.7.3 does not work on node 18
2. need to set --openssl-legacy-provider because webpack is using
   openssl in a legacy way that was changed in node 17.

Fixes https://github.com/github/vscode-codeql/issues/1373

I'm reticent to merge this change even if it does work since we are pointing directly to a git repo and an unreleased sha for `source-map`. If a new release is not made before we need to upgrade to node 18, we may need to fork the repo and release a version ourselves.

## Checklist

- [n/a] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [x] Issues have been created for any UI or other user-facing changes made by this pull request.
- [x] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/codeql-for-visual-studio-code) repo and add the `ready-for-doc-review` label there.

### CODE REVIEW

**Comment by elenatanasoiu** [comment]
> I'm reticent to merge this change even if it does work since we are pointing directly to a git repo and an unreleased sha for source-map.

I think the danger with this approach is that we might forget to replace the unreleased SHA with an official version of `source-map` as there's nothing prompting us to check for a newer version when we need to switch to Node 18.

Since the ultimate goal of this is to unblock us to use Node 18, I'd be inclined to suggest we wait until we'll need to run on 18 instead of half-heartedly upgrading `source-map` now. We'll then be prompted to upgrade source-map as part of that process and by that time it's likely an official version will be released.

What do you think?

**Comment by aeisenberg** [comment]
There's no rush to upgrade right now, but also, the request to upgrade source-map has been open for a while and there still hasn't been a release.

My concern is that when vscode moves to node 18, this extension will be broken until we get a new version of source-map (and fix the other problems). At this point, we're going to need to scramble to fix it fast.

It's hard to tell how often vscode updates its node versions. Maybe every 8 months? And the last time was in March. I don't want to get blindsided by this in the future, but we don't need to fix this _now_.

**Comment by elenatanasoiu** [comment]
@aeisenberg Good news! Looks like a fix was merged into source-map to fix the failing build (in Oct 2020): https://github.com/mozilla/source-map/issues/423. 

And a new release ([0.7.4](https://github.com/mozilla/source-map/tags)) containing the fix was pushed 10 days ago. Which is quite Nice of them. ;)

I've just tested this ([branch](https://github.com/github/vscode-codeql/compare/elenatanasoiu/node-18?expand=1))with the steps described [in the original issue](https://github.com/github/vscode-codeql/issues/1373) and the build now works correctly.

**Comment by aeisenberg** [comment]
Thanks for looking into this. That's good news. Would you mind pushing up your change?

**Comment by aeisenberg** [comment]
Closing in favour of #1378.

**Pull request closed without merging**
