### PR TITLE
Don't focus after delete

### PR DESCRIPTION
**Pull request by elenatanasoiu**
After you delete a query item from history, don't focus on a different item and just close the current query window.

This was requested by our designer when discussing the behaviour of variant analysis queries once a query is deleted. (See feedback in linked internal issue). 

For consistency, I've chosen to do the same for local & remote queries. 

## Checklist

- [ ] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [ ] Issues have been created for any UI or other user-facing changes made by this pull request.
- [ ] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/codeql-for-visual-studio-code) repo and add the `ready-for-doc-review` label there.

### CODE REVIEW

**Comment by elenatanasoiu** [comment]
CI still failing due to flakiness, not the changes in this PR.

**Review by norascheuch — APPROVED** [review]
Tested locally: 🚀

**Comment by elenatanasoiu** [comment]
This is still failing because of an ordering issue. :fishsticks:

**Comment by elenatanasoiu** [comment]
I've run out of steam in terms of debugging this. As far as I can tell the tree view always expects a current element to be set, so removing an item and not providing a new element to focus on leaves it in a bad state.

I think at this point it's wise to walk away and let the extension focus on a different item.

**Pull request closed without merging**
