### PR TITLE
Only include method signature in JumpToUsageMessage

### PR DESCRIPTION
**Pull request by robertbrignull**
Updates the `JumpToUsageMessage` to not include the full `Method` and `Usage` objects, but instead to identify the method by its signature and let the modeling store provide the full content.

## Checklist

- [ ] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [ ] Issues have been created for any UI or other user-facing changes made by this pull request.
- [ ] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/codeql-for-visual-studio-code) repo and add the `ready-for-doc-review` label there.

### CODE REVIEW

**Review by charisk — APPROVED** [review]
LGTM. What do you think about also renaming the message to be jump to _method_ rather than jump to _usage_? Seems like that's what it's doing.

**Comment by robertbrignull** [comment]
> What do you think about also renaming the message to be jump to _method_ rather than jump to _usage_?

Sounds good to me and definitely clearer.

**Comment by robertbrignull** [comment]
I've renamed from `JumpToUsage` to `JumpToMethod` throughout. This includes:
- Various method names
- A react view message
- An internal command
- A UI-interaction telemetry message

Everything being changed is internal so I think it's fine to just change it without any worries of compatibility or transition period.

**Comment by robertbrignull** [comment]
@koesie10 noticed that this PR accidentally broke jumping to usages in the method usages panel. I've opened https://github.com/github/vscode-codeql/pull/2977 to fix this.

**Pull request merged**
