### PR TITLE
Enable eqeqeq ESLint rule and fix violations

### PR DESCRIPTION
**Pull request by charisk**
Enforce use of === and !== and update places where we're not. See https://eslint.org/docs/latest/rules/eqeqeq for details.

Please shout if there are reasons we should not do this.

## Checklist
N/A:
- [ ] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [ ] Issues have been created for any UI or other user-facing changes made by this pull request.
- [ ] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/codeql-for-visual-studio-code) repo and add the `ready-for-doc-review` label there.

### CODE REVIEW

**Review by shati-patel — APPROVED** [review]
Seems very reasonable to me 👀 Though we can wait for a second opinion from someone with more historical context 😅

**Comment by charisk** [comment]
> Seems very reasonable to me 👀 Though we can wait for a second opinion from someone with more historical context 😅

Yeah I'll leave it open for now.

**Review by robertbrignull — COMMENTED** [review]
Sounds good to me too as an idea. I also don't have historical context and haven't yet looked in detail at each change, but I could do to see if it'll be behaviour changing or not.

**Review by koesie10 — APPROVED** [review]
LGTM too. I think the comparisons with `undefined` are the only ones that could potentially change behaviour because `null == undefined`, but according to the types these should never be `null`.

**Comment by charisk** [comment]
Thanks everyone for the reviews. I'll go ahead and merge it. @aeisenberg please shout if you see an issue with the change!

**Pull request merged**
