### PR TITLE
Create data model types for query history and start using them

### PR DESCRIPTION
**Pull request by norascheuch**
Replace this with a description of the changes your pull request makes.

## Checklist

- [ ] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [ ] Issues have been created for any UI or other user-facing changes made by this pull request.
- [ ] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/codeql-for-visual-studio-code) repo and add the `ready-for-doc-review` label there.

### CODE REVIEW

**Comment by charisk** [comment]
Any chance we could get the first commit in a separate PR (so that we can quickly review and get that out of the way)? It feels almost unrelated to the fact that we're adding data models - it's just something we came across when looking at that piece of work.

**Comment by norascheuch** [comment]
Sure! https://github.com/github/vscode-codeql/pull/2231

**Comment by charisk** [comment]
Is this ready for review? (Currently "draft")

**Comment by norascheuch** [comment]
Replaced by https://github.com/github/vscode-codeql/pull/2242 because the GH outage affected the branch history.

**Pull request closed without merging**
