### PR TITLE
Retry integration tests only on segfault

### PR DESCRIPTION
**Pull request by jcreedcmu**
Whenever https://github.com/microsoft/vscode-test releases 1.4.0, which includes 
https://github.com/microsoft/vscode-test/pull/56, we can merge this PR.

Fixes https://github.com/github/vscode-codeql/issues/263.

### CODE REVIEW

**Comment by aeisenberg** [comment]
Nice. It looks safe to merge now. On current VSCode, the retry will just never be triggered, so the behaviour would be the same.

**Comment by aeisenberg** [comment]
This looks good. Feel free to merge when 1.4.0 is out.

**Comment by jcreedcmu** [comment]
Right, I do want to wait until the change to `vscode-test` lands, because otherwise the behavior on our end is that we *won't* retry when we get a SIGSEGV.

**Comment by jcreedcmu** [comment]
(Also, this PR needs to include a rush-managed change to `package.json` that actually pins to version 1.4.0 of `vscode-test`, and I am waiting until that lands, rather than manually changing the lockfile, in case their dependencies change)

**Comment by jcreedcmu** [comment]
Looks like `vscode-test` might actually be releasing 1.4.0 soon, and https://github.com/microsoft/vscode-test/issues/63 shows someone else is also interested in https://github.com/microsoft/vscode-test/pull/56 landing.

**Comment by jcreedcmu** [comment]
I tested by pushing ddd9f734 above and confirming that tests correctly failed without retries.

**Pull request merged**
