### PR TITLE
Simplify location URLs if start and end line are the same

### PR DESCRIPTION
**Pull request by Marcono1234**
When the start and end line of a result are the same, currently the extension creates location URLs which specify both line numbers, e.g. `...MyFile.js#L5-L5`. This is appears to be redundant and can be simplified to just `#L5`.

I am not very familiar with this project, so any feedback is appreciated!

## Checklist

- [x] [CHANGELOG.md](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/CHANGELOG.md) has been updated to incorporate all user visible changes made by this pull request.
- [ ] Issues have been created for any UI or other user-facing changes made by this pull request.
- [ ] _[Maintainers only]_ If this pull request makes user-facing changes that require documentation changes, open a corresponding docs pull request in the [github/codeql](https://github.com/github/codeql/tree/main/docs/codeql/codeql-for-visual-studio-code) repo and add the `ready-for-doc-review` label there.

### CODE REVIEW

**Comment by aeisenberg** [comment]
This looks great. Thank you for your contribution. One minor thing I would like to see is that with this change is that the test is no longer showing any multiline results (arguably this was a limitation of the test before, but there was only a single code path earlier). But, could you add at least one multiline result in one of the test files, like `result-1-github-codeql.md`? You'd also need to update the corresponding test input in `analyses-results.json`. I think this is straight forward, but if not, I can take a look.

**Comment by aeisenberg** [comment]
Failing test is likely a flake.

**Comment by Marcono1234** [comment]
> One minor thing I would like to see is that with this change is that the test is no longer showing any multiline results

I am not completely sure what you mean. If you had written "still shows multiline results", then I would have assumed you mean that something like `#L1-L5` is unaffected, and that actually appears to be the case, see for example:
https://github.com/github/vscode-codeql/blob/788eb2b663d22fce2048319eb8717b9f3922a528/extensions/ql-vscode/test/unit-tests/data/markdown-generation/interpreted-results/path-problem/expected/result-2-meteor-meteor.md?plain=1#L51
https://github.com/github/vscode-codeql/blob/788eb2b663d22fce2048319eb8717b9f3922a528/extensions/ql-vscode/test/unit-tests/data/markdown-generation/interpreted-results/problem/expected/result-1-github-codeql.md?plain=1#L3

So, what did you mean by that?

**Comment by aeisenberg** [comment]
Apologies for that. You are correct. I missed those extra tests. Thanks for pointing them out. This PR looks great.

**Review by aeisenberg — APPROVED** [review]

**Pull request merged**
